import Head from "next/head";
import Avatar from "../components/Avatar";
import {
  ViewGridIcon,
  SearchIcon,
  MicrophoneIcon,
} from "@heroicons/react/solid";
import Image from "next/image";
import Footer from "../components/Footer";

import { useRef } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const searchInputRef = useRef(null);
  const router = useRouter();

  const handleSearch = (e) => {
    e.preventDefault();
    const searchTerm = searchInputRef.current.value;
    if (!searchTerm) return;
    router.push(`/search?term=${searchTerm}`);
  };

  return (
    <div className="flex flex-col h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <header className="flex w-full p-5 justify-between text-sm text-gray-700">
        {/* left menu */}
        <div className="header-link-group">
          <span className="link">About</span>
          <span className="link">Store</span>
        </div>

        {/* right menu */}
        <div className="header-link-group">
          <span className="link">Gmail</span>
          <span className="link">Images</span>
          {/* icon */}
          <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer" />
          {/* avatar */}
          <Avatar url="https://avatars.githubusercontent.com/u/66380727?v=4" />
        </div>
      </header>
      <main>
        {/* body */}
        <form className="flex flex-col items-center  mt-44">
          <Image
            src="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
            width={300}
            height={100}
            alt="Google Logo"
          ></Image>
          <div className="flex w-full mt-5 max-w-md rounded-full border border-gray-200 px-5 py-3 items-center hover:shadow-lg focus-within:shadow-lg sm:max-w-xl lg:max-w-2xl">
            <SearchIcon className="h-5 mr-3 text-gray-500 "></SearchIcon>
            <input
              ref={searchInputRef}
              type="text"
              className="flex-grow  focus:outline-none"
            />
            <MicrophoneIcon className="h-5 mr-3 text-gray-500 "></MicrophoneIcon>
          </div>

          <div className="flex flex-col space-y-2 w-1/2 justify-center mt-8 sm:flex-row sm:space-y-0 sm:space-x-4">
            <button className="btn" onClick={handleSearch}>
              Google Search
            </button>
            <button className="btn">I'm Feeling Lucky</button>
          </div>
        </form>
      </main>
      <div className="filler flex-grow"></div>
      <Footer></Footer>
    </div>
  );
}
